// Named permission keys — components call can('key'), never check role strings directly
import type { Role } from './roles';

export const PERMISSIONS = {
  // Applications
  APPLICATIONS_SUBMIT:    'applications.submit',
  APPLICATIONS_APPROVE:   'applications.approve',
  APPLICATIONS_VIEW_ALL:  'applications.view_all',

  // Gate pass
  GATEPASS_REQUEST:  'gatepass.request',
  GATEPASS_APPROVE:  'gatepass.approve',
  GATEPASS_VERIFY:   'gatepass.verify',

  // Issues
  ISSUES_CREATE:    'issues.create',
  ISSUES_MANAGE:    'issues.manage',
  ISSUES_VIEW_ALL:  'issues.view_all',

  // Notices
  NOTICES_POST:    'notices.post',
  NOTICES_VIEW:    'notices.view',

  // Messaging
  GROUPS_CREATE:   'groups.create',
  MESSAGES_SEND:   'messages.send',

  // Attendance
  ATTENDANCE_MARK:  'attendance.mark',
  ATTENDANCE_VIEW:  'attendance.view',

  // Payments
  PAYMENTS_UPLOAD:   'payments.upload',
  PAYMENTS_VERIFY:   'payments.verify',
  PAYMENTS_VIEW_ALL: 'payments.view_all',

  // Admin
  ADMIN_USERS:      'admin.users',
  ADMIN_ORG:        'admin.org',
  ADMIN_SETTINGS:   'admin.settings',
  AUDIT_VIEW:       'audit.view',
  ANALYTICS_VIEW:   'analytics.view',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Role → permissions map (mirrors RLS policies)
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  student: [
    PERMISSIONS.APPLICATIONS_SUBMIT,
    PERMISSIONS.GATEPASS_REQUEST,
    PERMISSIONS.ISSUES_CREATE,
    PERMISSIONS.NOTICES_VIEW,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.PAYMENTS_UPLOAD,
  ],
  teacher: [
    PERMISSIONS.APPLICATIONS_APPROVE,
    PERMISSIONS.GATEPASS_APPROVE,
    PERMISSIONS.ISSUES_VIEW_ALL,
    PERMISSIONS.NOTICES_POST,
    PERMISSIONS.NOTICES_VIEW,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.GROUPS_CREATE,
  ],
  hod: [
    PERMISSIONS.APPLICATIONS_APPROVE,
    PERMISSIONS.APPLICATIONS_VIEW_ALL,
    PERMISSIONS.GATEPASS_APPROVE,
    PERMISSIONS.ISSUES_VIEW_ALL,
    PERMISSIONS.NOTICES_POST,
    PERMISSIONS.NOTICES_VIEW,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.GROUPS_CREATE,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  warden: [
    PERMISSIONS.GATEPASS_APPROVE,
    PERMISSIONS.ISSUES_MANAGE,
    PERMISSIONS.ISSUES_VIEW_ALL,
    PERMISSIONS.NOTICES_VIEW,
    PERMISSIONS.MESSAGES_SEND,
  ],
  canteen: [
    PERMISSIONS.ISSUES_MANAGE,
    PERMISSIONS.ISSUES_VIEW_ALL,
    PERMISSIONS.NOTICES_VIEW,
    PERMISSIONS.MESSAGES_SEND,
  ],
  accounts: [
    PERMISSIONS.PAYMENTS_VERIFY,
    PERMISSIONS.PAYMENTS_VIEW_ALL,
    PERMISSIONS.NOTICES_VIEW,
    PERMISSIONS.MESSAGES_SEND,
  ],
  security: [
    PERMISSIONS.GATEPASS_VERIFY,
  ],
  admin: [
    PERMISSIONS.APPLICATIONS_VIEW_ALL,
    PERMISSIONS.GATEPASS_APPROVE,
    PERMISSIONS.ISSUES_VIEW_ALL,
    PERMISSIONS.NOTICES_POST,
    PERMISSIONS.NOTICES_VIEW,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.PAYMENTS_VIEW_ALL,
    PERMISSIONS.ADMIN_USERS,
    PERMISSIONS.ADMIN_ORG,
    PERMISSIONS.ADMIN_SETTINGS,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.GROUPS_CREATE,
    PERMISSIONS.ATTENDANCE_VIEW,
  ],
  principal: [
    PERMISSIONS.APPLICATIONS_APPROVE,
    PERMISSIONS.APPLICATIONS_VIEW_ALL,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.NOTICES_VIEW,
  ],
};
